- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: cedcea550c495d536247ca23115035b17074cac7
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: flake8
  - id: trailing-whitespace

- repo: git://github.com/pre-commit/mirrors-pylint
  sha: v1.5.2
  hooks:
  - id: pylint
